# Generated by Django 4.2.3 on 2023-09-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_partnershipform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('firstname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('area_of_interest', models.CharField(choices=[('Charity of the Year partnership', 'Charity of the Year partnership'), ('Support a Project', 'Support a Project'), ('In-kind donations', 'In-kind donations'), ('Raise funds in memory of a loved one', 'Raise funds in memory of a loved one'), ('Cause-related marketing', 'Cause-related marketing'), ('Raise funds to celebrate a special occasion', 'Raise funds to celebrate a special occasion')], max_length=255)),
                ('summary_of_proposed_partnership', models.TextField(max_length=800)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('fundraising_amount', models.CharField(choices=[('100', '100'), ('100-500', '100-500'), ('500-1000', '500-1000'), ('1000-3000', '1000-3000')], max_length=255)),
                ('submission_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='library_pictures/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('firstname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('summary_of_proposed_partnership', models.TextField(max_length=800, verbose_name='Summary of Proposed Partnership')),
            ],
            options={
                'verbose_name': 'Partnership Inquiry',
                'verbose_name_plural': 'Partnership Inquiries',
            },
        ),
    ]
