# Generated by Django 4.2.3 on 2023-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_fundraiser_librarypictures_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ManyToManyField(blank=True, to='home.team'),
        ),
    ]
