# Generated by Django 4.2.3 on 2023-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_team_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='img',
        ),
        migrations.AddField(
            model_name='team',
            name='img',
            field=models.ImageField(default=1, upload_to='team_images'),
            preserve_default=False,
        ),
    ]
