# Generated by Django 4.2.3 on 2023-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_blog_images_blog_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('testimonial_text', models.TextField()),
                ('testimonial_image', models.ImageField(upload_to='testimonial_images')),
            ],
        ),
    ]
