# Generated by Django 4.2.3 on 2023-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembers',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
